title: Chemical Process Problem Solving
description: Using theory to solve real chemical production problems
url: https://chem.zhanghd.fun
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-seo-tag

# GA4（不要 UA）
google_analytics: G-0TB5EFN78M
