title: "Chemical Process Problem Solving"
description: "Using theory to solve real chemical production problems."
baseurl: ""
url: "https://chem.zhanghd.fun"
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
google_analytics: UA-XXXXXXX-X